### ISSUE TITLE
Absence de HorsDePlanimetrique

### ISSUE THREAD

**Issue by mthh** [ANRChoucas/Ruitor#11]
J'ai l'impression qu'il manque `HorsDePlanimetrique` dans l'ontologie.
Est-ce qu'il serait possible que tu le rajoutes ? (j'essayais de rejouer l'alerte *Grand Veymont* dans Gaspar)

**Comment by MBunel** [comment]
Je ne peux pas tester tout de suite, mais normalement tu peux "émuler" `HorsDePlanimétrique` en ajoutant le modifieur `Not` à `DansPlanimetrique` (comme tu l'as fait dans cette issue #12 )

**Comment by MBunel** [comment]
Corrigé dans la branche fix_mmth

**Comment by mthh** [comment]
Sauf erreur de ma part, en utilisant la version du dernier commit de la branche fix_mmth, `HorsDePlanimetrique` ne fonctionne toujours pas (et `AOuestDe` ne fonctionne plus - alors qu'en utilisant la version du commit précédent `AOuestDe` fonctionne bien).

**Comment by MBunel** [comment]
C'est normal qu'il ne fonctionne pas encore, il dépend de DansPlanimétrique et je n'ai pas encore corrigé l'issue #10

Par contre pour à l'ouestDe c'est pas normal, je me suis trompé lorsque j'ai modifié l'ontologie.

**Comment by mthh** [comment]
> C'est normal qu'il ne fonctionne pas encore, il dépend de DansPlanimétrique et je n'ai pas encore corrigé l'issue #10 

D'acc, pas de pbm (au cas où je précise que ça renvoi *Internal Server Error*, et pas juste que toutes les cellules ont la même valeur comme avec DansPlanimetrique)

**Comment by MBunel** [comment]
Pour le HorsDePlanimétrique ? C'est pas normal, j'ai du faire une erreur (je peux pas lancer le serveur pour tester sur cette machine)

**Comment by mthh** [comment]
Oui, sur la version du dernier commit, HorsDePlanimetrique et AOuestDe renvoient *Internal Server Error*.

> (je peux pas lancer le serveur pour tester sur cette machine)

Pas de soucis, c'est pour ça que je te fais le retour pendant que j'ai Ruitor qui tourne !

**Comment by MBunel** [comment]
Voilà les deux devraient marcher normalement maintenant

**Comment by mthh** [comment]
Effectivement, ça fonctionne correctement pour HorsDePlanimetrique, AOuestDe et DansPlanimetrique !
Merci !
