### ISSUE TITLE
Utilisation de DistanceQuantitativePlanimetrique

### ISSUE THREAD

**Issue by mthh** [ANRChoucas/Ruitor#12]
Est-ce qu'il est possible de spécifier la distance à utiliser en utilisant l'API web pour la relation `DistanceQuantitativePlanimetrique` ?
J'ai vu dans la doc qu'on pouvait passer une liste de modifieurs quand on choisit la relation de localisation à utiliser, donc j'ai essayé de faire une requête avec un objet comme ça
```json
{
  "zir":[934813.563802895,6441833.827302791,944321.8725463923,6450175.888036326],
  "relationLocalisation":
    {
      "uri":"http://www.semanticweb.org/mbunel/ontologies/Ornitho#DistanceQuantitativePlanimetrique",
      "modifieurs":[{"uri":"http://www.semanticweb.org/mbunel/ontologies/Ornitho#EqVal","value":800}]
    },
  "site":{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[942832.0000000009,6445523.399999988]}}]}
}
```

mais ça ne fonctionne pas (*Internal Server Error*, rien de loggé).
J'imagine que ce n'est pas comme ça qu'il faut faire (et en regardant dans ton manuscrit, je ne suis pas sûr que la distance que je cherche à utiliser, 800 mètres par ex., soit un *modifieur* donc ça explique peut-être pourquoi ça ne fonctionne pas ?)

C'est toujours pour l'alerte *Grand Veymont* même si j'ai repris la zir et le site de l'issue précédente pour l'exemple.
Désolé pour les différentes issues, normalement c'était la dernière !

**Comment by MBunel** [comment]
Je ne me rappelle pas si j'ai implémenté la surcharge des paramètres par défaut. Je crois que j'avais un peu commencé, mais je dois vérifier ça. Sinon il faudra modifier directement  le fuzzyficateur.

**Comment by MBunel** [comment]
Bon ce n'est pas implémenté. Malheureusement, je ne vais pas avoir le temps de le faire rapidement. La méthode officielle (et parfaitement documentée ;-)  )  est  de modifier manuellement dans l'ontologie le triplet :

```xml
<rdf:Description rdf:about="http://www.semanticweb.org/mbunel/ontologies/Ornitho#EqDist">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://www.semanticweb.org/mbunel/ontologies/Ornitho#EqVal"/>
	<Ornitho:pythonName>EqVal</Ornitho:pythonName>
      <Ornitho:pythonParameter>{'value':0}</Ornitho:pythonParameter>
</rdf:Description>
```

pour fixer la valeur de la distance. Pour une distance de 50 m on aura :

```xml
<rdf:Description rdf:about="http://www.semanticweb.org/mbunel/ontologies/Ornitho#EqDist">
	<rdf:type rdf:resource="http://www.w3.org/2002/07/owl#Class"/>
	<rdfs:subClassOf rdf:resource="http://www.semanticweb.org/mbunel/ontologies/Ornitho#EqVal"/>
	<Ornitho:pythonName>EqVal</Ornitho:pythonName>
	<Ornitho:pythonParameter>{'value':50}</Ornitho:pythonParameter>
</rdf:Description>
```

**Comment by mthh** [comment]
Entendu, merci.

J'ai essayé et j'ai un petit doute sur le raster qui m'est renvoyé (ça me faisait ça avec le MNT que j'utilisais, du coup j'ai essayé avec le MNT fourni (BR.tif) dans le repository de Ruitor, cf. image).
C'est bien censé être ça ? Le "cercle" me paraissait moins discontinu dans les images de ton manuscrit.

![distancePlanimetrique](https://user-images.githubusercontent.com/12172162/140771331-6aa08658-9610-48b2-bc50-ce83678c352b.png)

<details>
<summary>Détails</summary>

La requête:
```
curl 'http://localhost:8000/spatialisation?confiance=1' \
   --data-raw '{"zir":[934813.563802895,6441833.827302791,944321.8725463923,6450175.888036326],"relationLocalisation":{"uri":"http://www.semanticweb.org/mbunel/ontologies/Ornitho#DistanceQuantitativePlanimetrique"},"site":{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[942832.0000000009,6445523.399999988]}}]}}'
```

et dans l'ontologie, comme tu as dit,

```
...
<Ornitho:pythonParameter>{'value':800}</Ornitho:pythonParameter>
...
```


</details>

**Comment by MBunel** [comment]
Ah oui, j'avais oublié de surcharger le paramètre `step` qui indique la largeur de la fonction d'appartenance. Le dernier commit de Fix_mmth devrait marcher. Tu peux modifier la valeur de `step` comme celle de `value` si tu en as besoin, mais normalement 100m c'est une valeur qui est assez passe-partout pour cette relation

**Comment by mthh** [comment]
Entendu, je teste ça demain, merci.

**Comment by mthh** [comment]
Parfait pour `step`.
J'ai implémenté un truc à l'arrache pour quand même passer la distance souhaitée pour `DistanceQuantitativePlanimetrique` dans les `modifieurs` de la requête Web (c'est trop à l'arrache pour mériter une PR mais ça à le mérite d'exister ;) merci pour les infos sur ces histoires de distance !)
